"""add financial profile fields

Revision ID: 388acb48fac4
Revises: b672d2b00bbe
Create Date: 2026-07-27 17:25:31.152861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '388acb48fac4'
down_revision: Union[str, None] = 'b672d2b00bbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_salaried', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('users', sa.Column('basic_salary', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('other_deductions', sa.Float(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('existing_80c', sa.Float(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('existing_80d', sa.Float(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('years_to_goal', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'years_to_goal')
    op.drop_column('users', 'existing_80d')
    op.drop_column('users', 'existing_80c')
    op.drop_column('users', 'other_deductions')
    op.drop_column('users', 'basic_salary')
    op.drop_column('users', 'is_salaried')
    # ### end Alembic commands ###
