"""add goal inflation_rate

Revision ID: b672d2b00bbe
Revises: e9d198a7c1e3
Create Date: 2026-07-21 22:55:35.970834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b672d2b00bbe'
down_revision: Union[str, None] = 'e9d198a7c1e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('inflation_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'inflation_rate')
    # ### end Alembic commands ###
